---
- hosts: users
  become: yes
  tasks:
      - name: ipv6 off
        lineinfile:
            dest: /etc/sysctl.conf
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
        notify: restart sysctl
        with_items:
            - { regexp: '^net.ipv6.conf.all.disable_ipv6 = 1', line: 'net.ipv6.conf.all.disable_ipv6 = 1' }
            - { regexp: '^net.ipv6.conf.default.disable_ipv6 = 1', line: 'net.ipv6.conf.default.disable_ipv6 = 1' }
            - { regexp: '^net.ipv6.conf.lo.disable_ipv6 = 1', line: 'net.ipv6.conf.lo.disable_ipv6 = 1' }
              
              
  handlers:
      - name: restart sysctl
        shell: sysctl -p
